#!/bin/bash

repos:
- repo: local
  hooks:

  - id: black
    name: black
    entry: black
    language: system
    types: [python]
    exclude: pyisr/ui/resources.py
    args: [--line-length=88]
  
  - id: isort
    name: isort
    entry: isort
    language: system
    types: [python]
    args: ["--profile", "black", "--filter-files"]
  
  - id: codespell
    name: codespell
    entry: codespell
    language: system
    types: [python]
    args: [
      "docs tests",
      "*.py *.rst *.md",
    ]

  - id: flake8
    name: flake8
    entry: flake8
    language: python
    types: [python]
    additional_dependencies: [
      "flake8-black==0.3.2",
      # "flake8-isort==4.1.1", it causes issues with black
      # "flake8-quotes==3.3.1", it also causes issues with black
    ]
    

